title: <p align="center"> NBSRINI </p>
logo: /assets/img/NBS_Sample.png

description:
  <p align="center">
  <a href="https://github.com/nbsrini">GitHub</a>
  
  <br>   
  I'm learning AI and ML course at Upgrad.
  <br>
  </p>



theme: jekyll-theme-minimal
